name: My GitHub Actions Workflow
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Git version
        run: git --version
      - uses: actions/checkout@v3.3.0
        with:
          ref: master
        # add the GIT_STRATEGY variable here
        env:
          GIT_STRATEGY: clone
      - name: Use Node.js 16
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16
      - name: Install dependencies and run build script
        run: |
          npm install
          npm run build
      - name: Run tests
        run: npm test
