name: My GitHub Actions Workflow
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.4
        with:
          ref: main # Replace 'main' with your branch name if it's different
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm install
      - name: Verify Cypress Installation
        run: npx cypress verify
      - name: Run Cypress Tests
        run: npx cypress run
